file_path <-file.choose()
library(stringr)
paragraph <- paste(readLines(file_path),collapse=" ")
print(paragraph)
clean_paragraph<- str_replace_all(paragraph,"[[:punct:]]","")
words <-unlist(strsplit(clean_paragraph,"\\s+"))
print(paste("Number of words:",length(words)))
word_length <- nchar(words)
avg_word_length <- mean(word_length)
#avg_word_length <- sum(word_length)/length(words)
cat("Average word length:", avg_word_length)
max_length <- max(word_length)
longest_word <-words[word_length==max_length]
cat("Longest word:",longest_word)
replaced_paragraph <-str_replace_all(clean_paragraph,"and","&")
cat("Actual Paragraph:",clean_paragraph)
cat("Replaced paragraph(and replaced with &)\n",replaced_paragraph)
